axl/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='bugtracker/')),
    url(r'^bugtracker/', include('bugtracker.urls')),
    url(r'^admin/', admin.site.urls, name='django_admin'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bugtracker/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import url
from .views import IndexView, LoginView, LogoutView, IssueListView, \
    IssueCreateView, IssueDetailView, IssueUpdateView, ProfileView, \
    UpdateDataUserView, update_password, EvaluationCommentCreate, ExportXlsx, \
    IssueEvaluationView, IssueEvaluationResultView, \
    IssueEvaluationResulExportXlsx, IssueEvaluationDetails, IssueEvaluationFilter

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/(?P<u_name>[-_\w]+)/$', ProfileView.as_view(),
        name="profile"),
    url(r'^update_user/$', UpdateDataUserView.as_view(), name="update_user"),
    url(r'^update_password/$', update_password, name="update_password"),
    url(r'^home/$', IssueListView.as_view(), name='home'),
    url(r'^create/$', IssueCreateView.as_view(), name='create'),
    url(r'^detail/(?P<id_issue>[-_\w]+)/$', IssueDetailView.as_view(),
        name='detail'),
    url(r'^update/(?P<id_issue>[-_\w]+)/$', IssueUpdateView.as_view(),
        name='update'),
    url(r'add_evaluation_comment/$', EvaluationCommentCreate.as_view()),
    url(r'xlsx/$', ExportXlsx.as_view(), name='xlsx'),
    url(r'xlsx_results/$', IssueEvaluationResulExportXlsx.as_view(),
        name='xlsx_results'),
    url(r'^issue_evaluation/$', IssueEvaluationView.as_view(),
        name='issue_evaluation'),
    url(r'^issue_evaluation/result/$', IssueEvaluationResultView.as_view(),
        name="issue_evaluation_results"),
    url(r'^issue_evaluation/(?P<id_issue>[-_\w]+)/$',
        IssueEvaluationDetails.as_view(),
        name="issue_evaluation_result_results"),
    url(r'^issue_evaluation/filter/result/$', IssueEvaluationFilter.as_view(),
        name="issue_evaluation_filter_est"),
]

bugtracker/models.py
# -*- encoding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class SoftwareIssue(models.Model):
    software = models.CharField(max_length=200)

    class Meta:
        ordering = ('software',)

    def __unicode__(self):
        return self.software


class PriorityIssue(models.Model):
    priority = models.CharField(max_length=200)
    fa_icon = models.CharField(max_length=30, null=True)


    class Meta:
        ordering = ('priority',)

    def __unicode__(self):
        return self.priority


class StatusIssue(models.Model):
    status = models.CharField(max_length=200)
    show_in_main_list = models.BooleanField(default=True, blank=False)
    bg_color = models.CharField(max_length=7, null=True)

    class Meta:
        ordering = ('status',)

    def __unicode__(self):
        return self.status


class ReproducibilityIssue(models.Model):
    reproducibility = models.CharField(max_length=200)

    class Meta:
        ordering = ('reproducibility',)

    def __unicode__(self):
        return self.reproducibility


class Headquarter(models.Model):
    headquarter = models.CharField(max_length=200)

    class Meta:
        ordering = ('headquarter',)

    def __unicode__(self):
        return self.headquarter


class BrowserIssue(models.Model):
    browser = models.CharField(max_length=200)
    fa_icon = models.CharField(max_length=30, null=True)

    class Meta:
        ordering = ('browser',)

    def __unicode__(self):
        return self.browser


class OsIssue(models.Model):
    os = models.CharField(max_length=200)
    fa_icon = models.CharField(max_length=30, null=True)

    class Meta:
        ordering = ('os',)

    def __unicode__(self):
        return self.os


class TypeIssue(models.Model):
    type_issue = models.CharField(max_length=100)
    fa_icon = models.CharField(max_length=30, null=True)

    class Meta:
        ordering = ('type_issue',)

    def __unicode__(self):
        return self.type_issue


class CategoryIssue(models.Model):
    category_issue = models.CharField(max_length=100)

    class Meta:
        ordering = ('category_issue',)

    def __unicode__(self):
        return self.category_issue


class Person(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    cellphone = models.CharField(max_length=20, blank=True)
    extension = models.CharField(max_length=10, blank=True)
    headquarter = models.ForeignKey(Headquarter, on_delete=models.CASCADE)
    dev = models.BooleanField(default=False)

    class Meta:
        ordering = ('user__first_name',)

    def __unicode__(self):
        return self.user.first_name + ' ' + self.user.last_name


class Issue(models.Model):
    issue = models.CharField(max_length=300,)
    description = models.TextField()
    software = models.ForeignKey(SoftwareIssue, on_delete=models.CASCADE)
    headquarter = models.ForeignKey(Headquarter, on_delete=models.CASCADE)
    browser = models.ForeignKey(BrowserIssue, on_delete=models.CASCADE)
    os = models.ForeignKey(OsIssue, on_delete=models.CASCADE)
    priority = models.ForeignKey(PriorityIssue, on_delete=models.CASCADE)
    type_issue = models.ForeignKey(TypeIssue, on_delete=models.CASCADE)
    category_issue = models.ForeignKey(CategoryIssue, on_delete=models.CASCADE)
    reproducibility_issue = models.ForeignKey(
        ReproducibilityIssue, on_delete=models.CASCADE)
    steps_to_reproduce = models.TextField(blank=True, null=True)
    evaluation_comments = models.TextField(blank=True, null=True)
    status = models.ForeignKey(
        StatusIssue, on_delete=models.CASCADE, blank=True, null=True)
    evaluated = models.BooleanField(default=False)
    dev = models.ForeignKey(
        Person, on_delete=models.CASCADE, null=True, related_name='Developer')
    ticket = models.CharField(max_length=6, null=True, blank=True)
    sprint = models.CharField(max_length=6, null=True, blank=True)
    reporter = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name='Persons')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image1 = models.ImageField(
        upload_to='uploads/', max_length=1500, blank=True)
    image2 = models.ImageField(
        upload_to='uploads/', max_length=1500, blank=True)

    def get_absolute_url(self):
        return reverse('issue-detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.issue


class EvaluationComment(models.Model):
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name='Evaluator')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)


class IssueEvaluation(models.Model):
    class Meta:
        permissions = (
            ("can_view_results_evaluations", "Can view evaluations results"),
        )
    time_evaluation = models.TextField()
    resolve = models.TextField()
    difficulty = models.TextField()
    contact = models.TextField()
    satisfied = models.TextField()
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name='EvalUser')
    issue = models.ForeignKey(
        Issue, on_delete=models.CASCADE, null=True, related_name='EvalIssue')
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

bugtracker/templates/bugtracker/create.html
{% extends "bugtracker/index.html" %}
{% block content %}
    <h3 class="text-center">Registrar incidencia</h3>
    <hr>

    {% include "includes/messages.html" %}


        <div class="row">
            <form id="issue-udapte-form" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-lg-offset-2 col-md-8">
                    <div class="input-field col-sm-12 ">
                        <label>Título: <span style="color: red;"> * </span> </label>
                        {{ form.issue }}
                    </div>
                    <div class="col-sm-12">
                        <label>Descripción: <span style="color: red;"> * </span> </label>
                        {{ form.description }}
                    </div>
                    <div class="col-sm-12">
                        <label>Pasos para reproducirlo: <span style="color: red;"> * </span> </label>
                        {{ form.steps_to_reproduce }}
                        <br>
                    </div>
                    <div class="col-md-6 file-field input-field">
                      <div class="btn-flat">
                        <span>Imagen1 (Opcional)</span>
                        {{ form.image1 }}
                      </div>
                    </div>
                    <div class="col-md-6 file-field input-field">
                      <div class="btn-flat">
                        <span>Imagen2 (Opcional)</span>
                        {{ form.image2 }}
                          <br>
                      </div>
                    </div>
                    <div class="col-md-6">
                        <label>Software: <span style="color: red;"> * </span> </label>
                        {{ form.software }}

                        <label>Sede: <span style="color: red;"> * </span> </label>
                        {{ form.headquarter }}

                        <label>Navegador: <span style="color: red;"> * </span> </label>
                        {{ form.browser }}

                        <label>Sistema operativo: <span style="color: red;"> * </span> </label>
                        {{ form.os }}
                    </div>
                    <div class="col-md-6">

                        <label>Prioridad: <span style="color: red;"> * </span> </label>
                        {{ form.priority }}

                        <label>Tipo: <span style="color: red;"> * </span> </label>
                        {{ form.type_issue }}

                        <label>Categoría: <span style="color: red;"> * </span> </label>
                        {{ form.category_issue }}

                        <label>Reproducibilidad: <span style="color: red;"> * </span> </label>
                        {{ form.reproducibility_issue }}

                        <br>
                    </div>
                    <div class="col-lg-12">
                        <input type="hidden" id="is_admin" value="false">
                        <a href="{% url 'home' %}" id="btn-to-back" class="btn btn-primary notify">
                            <i class="fa fa-arrow-left"></i> Volver
                        </a>
                        <button class="btn btn-success notify" type="button" id="btn-to-save" onclick="validateFormNewUpdateIssue()">
                          <i class="fa fa-save"></i> Actualizar incidencia
                        </button>
                    </div>
                </div>
            </form>
        </div>
    <hr>
{% endblock %}

bugtracker/templates/bugtracker/index.html
{% extends "base.html" %}
{% block nav %}
    {% include "includes/menu.html" %}
{% endblock %}

{% block content %}
    {% if not evalue %}

    <div class="messages">

        <div class="alert alert-primary alert-warning alert-dismissible text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong style="color: #a94442">Tiene incidencias pendientes por evaluar. <a class="btn btn-warning btn-sm" href="{% url 'home' %}?is_evaluated=on">
            Ver aqui
        </a></strong>
        </div>

    </div>

    {% endif %}
    <div class="row login-panel">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <ul class="list-group">
                        <li class="list-group-item active">
                            Incidencias por estado
                        </li>
                        {% for s_i in status_issues %}
                            <li class="list-group-item">
                                <span class="badge">{{ s_i.total }}</span>
                                <a href="{% url 'home' %}?status={{ s_i.status_id }}"
                                    data-toggle="tooltip" data-placement="top" title="Ver lista">
                                    {{ s_i.status__status }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <ul class="list-group">
                        <li class="list-group-item active">
                            Incidencias por prioridad
                        </li>
                        {% for p_i in priority_issues %}
                            <li class="list-group-item">
                                <span class="badge">{{ p_i.total }}</span>
                                <a href="{% url 'home' %}?priority={{ p_i.priority__id }}"
                                    data-toggle="tooltip" data-placement="top" title="Ver lista">
                                    {{ p_i.priority__priority }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <ul class="list-group">
                        <li class="list-group-item active">
                            Incidencias por tipo
                        </li>
                        {% for t_i in type_issues %}
                            <li class="list-group-item">
                                <span class="badge">{{ t_i.total }}</span>
                                <a href="{% url 'home' %}?type_issue={{ t_i.type_issue_id }}"
                                    data-toggle="tooltip" data-placement="top" title="Ver lista">
                                    {{ t_i.type_issue__type_issue }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

bugtracker/templates/bugtracker/update.html
{% extends "bugtracker/index.html" %}
{% block content %}
<h3 class="text-center">Actualizar incidencia: #{{ issue.id }}</h3>
    <hr>

{% include "includes/messages.html" %}

<div class="row">
    <form id="issue-udapte-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-lg-10 col-md-offset-1">

            {% if form.evaluation_comments.value %}
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="panel panel-default panel-danger"
                     style="background-color: #ffe6e6; margin-bottom: 10px;">
                    <div class="panel-body">
                        <strong>
                            <i class="fa fa-quote-left fa-3x fa-pull-left"
                               aria-hidden="true"></i>
                            La incidencia se encuentra en estado:
                            <i>'{{ form.instance.status.status|default_if_none:"Nueva" }}'</i>.
                            <br>
                            Concepto: {{ form.evaluation_comments.value }}
                        </strong>
                    </div>
                </div>
            </div>
            {% endif %}

            <div class="input-field col-sm-12 col-md-12 col-lg-12">
                <label>Reportado por:</label>
                {% for value, text in form.reporter.field.choices %}
                {% if value == form.reporter.value %}
                <h5>{{ text }}</h5>
                <input type="hidden" name="reporter" value="{{ value }}"/>
                {% endif %}
                {% endfor %}
            </div>
            <div class="input-field col-sm-12 col-md-12 col-lg-12">
                <label>Título: <span style="color: red;"> * </span> </label>
                {{ form.issue }}
                <br>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <label>Descripción: <span style="color: red;"> * </span> </label>
                {{ form.description }}
                <br>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <label>Pasos para reproducir: <span style="color: red;"> * </span> </label>
                {{ form.steps_to_reproduce }}
                <br>
            </div>
                <div class="col-sm-12 col-md-6 col-lg-6 file-field input-field">
                    <label>Imagen1 (Opcional)</label>
                    {{ form.image1 }}
                </div>
                <div class="col-sm-12 col-md-6 col-lg-6 file-field input-field">
                    <label>Imagen2 (Opcional)</label>
                    {{ form.image2 }}

                </div>
        </div>

        <div class="col-lg-10 col-md-10 col-md-offset-1">
            <hr>
            <div class="col-md-3">
                <div>
                <label>Software: <span style="color: red;"> * </span> </label>
                {{ form.software }}
                </div>
                <div>
                <label>Sede: <span style="color: red;"> * </span> </label>
                {{ form.headquarter }}
                </div>
                <div>
                <label>Navegador: <span style="color: red;"> * </span> </label>
                {{ form.browser }}
                </div>
                <div>
                <label>Sistema operativo: <span style="color: red;"> * </span> </label>
                {{ form.os }}
                </div>
            </div>
            <div class="col-md-3">
                <div>
                <label>Prioridad: <span style="color: red;"> * </span> </label>
                {{ form.priority }}
                </div>
                <div>
                <label>Tipo: <span style="color: red;"> * </span> </label>
                {{ form.type_issue }}
                </div>
                <div>
                <label>Categoría: <span style="color: red;"> * </span> </label>
                {{ form.category_issue }}
                </div>
                <div>
                <label>Reproducibilidad: <span style="color: red;"> * </span> </label>
                {{ form.reproducibility_issue }}
                    <br>
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    {% if form.dev and form.status and form.ticket and form.evaluation_comments %}
                          <div class="col-md-12">
                              <div class="panel panel-primary">
                                  <div class="panel-heading">
                                      <strong>Visible por Administradores y
                                          desarrolladores</strong>
                                  </div>
                                  <div class="panel-body">
                                      <label>Asignar a: <span style="color: red;"> * </span> </label>
                                      {{ form.dev }}
                                      <label>Estado: <span style="color: red;"> * </span> </label>
                                      {{ form.status }}
                                      <div class="row">
                                          <div class="col-md-6">
                                          <label>Ticket:</label>
                                          {{ form.ticket }}
                                          </div>
                                          <div class="col-md-6">
                                          <label>Sprint:</label>
                                          {{ form.sprint }}
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <input type="hidden" id="is_admin" value="true">
                          </div>
                        {% else %}
                        <input type="hidden" id="is_admin" value="false">
                    {% endif %}
                </div>
            </div>
            <div class="col-md-10 ">
            <a href="{{request.META.HTTP_REFERER}}" id="btn-to-back" class="btn btn-primary notify">
            <i class="fa fa-arrow-left"></i> Volver
            </a>
            <button class="btn btn-success notify" type="button" id="btn-to-save" onclick="validateFormNewUpdateIssue()">
              <i class="fa fa-save"></i> Actualizar incidencia
            </button>
        </div>
            <div class="col-md-12">
                <hr>
                <div class="panel panel-primary">
                    <a class="btn btn-default pull-right" data-toggle="modal"
                                                            data-target="#myModal">
                        <i class="fa fa-th-list"></i>
                        Agregar Comentario
                    </a>
                    <div class="panel-heading">
                        <strong>Comentarios registrados</strong>
                    </div>
                    <div class="panel-body" style="max-height: 400px; overflow: scroll;">
                        <div id="list-comments"></div>
                        <div id="content-comments">
                            {% for comment in comments %}
                                <div class="panel panel-info">
                                    <div class="panel-heading">
                                        {{ comment.user.first_name }}
                                        {{ comment.user.last_name }}
                                        </br>
                                        <small>
                                            {{comment.created_at | date:"d/m/Y H:i"}}
                                        </small>
                                    </div>
                                    <div class="panel-body">
                                        {{ comment.comment }}
                                    </div>
                                </div>
                            {% empty %}
                                <span class="label label-warning">
                                    No se han registrado comentarios
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
  function validateForm(){
    var validate = 0;
    var msj_error = "<ul>";

    //Validate Title
    if($("#id_issue").val() == ""){
      validate++;
      msj_error += "<li> El <b>Título</b> de la incidencia. </li>";
    }

    //Validate Desciption
    if($("#id_description").val() == ""){
      validate++;
      msj_error += "<li> La <b>Descripción</b> es requerida. </li>";
    }

    //Validate steps_to_reproduce
    if($("#id_steps_to_reproduce").val() == ""){
      validate++;
      msj_error += "<li> La <b>Descripción</b> es requerida. </li>";
    }

    //Validate Software
    if($("#id_software").val() == ""){
      validate++;
      msj_error += "<li> El <b>Software</b> es requerido. </li>";
    }

    //Validate Sede
    if($("#id_headquarter").val() == ""){
      validate++;
      msj_error += "<li> La <b>Sede</b> es requerida. </li>";
    }

    //Validate Navegador
    if($("#id_browser").val() == ""){
      validate++;
      msj_error += "<li> El <b>Navegador</b> es requerido. </li>";
    }

    //Validate OS
    if($("#id_os").val() == ""){
      validate++;
      msj_error += "<li> El <b>Sistema operativo</b> es requerido. </li>";
    }

    //Validate priority
    if($("#id_priority").val() == ""){
      validate++;
      msj_error += "<li> La <b>Prioridad</b> es requerida. </li>";
    }

    //Validate type_issue
    if($("#id_type_issue").val() == ""){
      validate++;
      msj_error += "<li> El <b>Tipo de Incidencia</b> es requerido. </li>";
    }

    //Validate Category_issue
    if($("#id_category_issue").val() == ""){
      validate++;
      msj_error += "<li> La <b>Categoría</b> es requerida. </li>";
    }

    //Validate Reproducibility_issue
    if($("#id_reproducibility_issue").val() == ""){
      validate++;
      msj_error += "<li> La <b>Reproducibilidad</b> es requerida. </li>";
    }

    var is_admin = $("#is_admin").val();
    if(is_admin == "true"){
      if($("#id_dev").val() == ""){
        validate++;
        msj_error += "<li> Debe asignar un <b>Responsable</b> a la incidencia. </li></ul>";
        sendForm2(validate, msj_error);
       }else{
         sendForm2(validate, msj_error);
       }
    }else{
       msj_error += "</ul>";
       sendForm2(validate, msj_error);
    }
  }

  function sendForm2(validate, msj_error){
    if(validate == 0){
      $("#btn-to-back").hide();
      $("#btn-to-save").attr('disabled', 'true');
      alertify.success("<i class='fa fa-spin fa-spinner'></i> Enviando un email de notificación.");
      $("#issue-udapte-form").submit();
    }else{
      alertify.error("Debe llenar los campos requeridos: <br/><br/>" + msj_error);
    }

  }
</script>

{% endblock %}